language: java
jdk:
- oraclejdk8
install: true
script: mvn test
deploy:
  provider: heroku
  api_key:
    secure: RpTigAY6+5WaL/ChYVIpB9r8+Swb/irHjiMC+gxLI6PZ10ZjsaG3LOBi4L/izdbOdDg9j7vrEg6rqKmRP/cJAZKg7lB/vwnXP1ULNNMCKUUmo5JJi04+0vWj7oZYVe812PPFJKaGlrQzIoD27gMh6Pbr3b0lNrvhegfWPL5oCQzVZVj/l1Tu+apggl63BuUrTm7cDfIL2M2WDgBi08mGZRv1BQ8kWWZF20XjKekJyHujKwt1CejN11nHHwC/DBUaL/6aJJIJMacY04stU/pBlUIDTwFSx+Hqqa1U3I52CnRCR+fbOy5rhrQyg26RG7RYhBpCut94L2rgN9ITPPN6neweHdzIU0MmCXxSyJpPmkXV77JUMhONSqwex+HBx+8D85tKxgqiDO//MKGAk9jLGrAXqdlZHWKxCY9pTDU79zZovCB1tCQMgCgr23n3ON13jR2CevNdZhBYfSLd+gG3Wj8p2PdejNXZ2yUamlNF1BqEBiMTXqY3SEa+iWBUfbY04JrRtUmuGms8qOHBAlAc7pNqTd2K4nIs0RbzctjJp6pNzXkfku2CjH5LRdC5k8GEznRW+ZqVx8/41D5dgGKYytNs85EguwwTtAIF3uMseHW4mN/Q6iHcZeqoJe9J4PUgvPF83L42oPVO8vZcnsbKnRrwmRDXOphP0QeE3OMpk4U=
  app: ws-citest
  on:
    repo: wstom/CITest
notifications:
  email:
    on_success: change
    on_failure: always
